### ISSUE TITLE
3D visualization for room

### ISSUE THREAD

**Issue by dikyridhlo** [3dcitydb/3dcitydb-web-map#69] opened 2021-09-02 03:21 UTC
I want to create 3D visualization for room, not the building.
So, I can click on a room and show its attribute.

Is it possible?

**Comment by thomashkolbe** [comment] 2021-09-02 06:58
No, not directly, because the 3DCityDB Exporter can only export so-called "top-level features" like Building, Road etc. as visualization objects that are clickable. 
But you can do a "hack" and use one (or maybe a few) SQL statement(s) and copy the tuples from the ROOM table into the table GENERIC_CITYOBJECT. Since GenericCityObjects are "top-level features" you can then export them as clickable objects using the KML/COLLADA/glTF exporter. If the attributes assigned to the rooms are generic attributes, you can also use the Spreadsheet Exporter to export them from the GenericCityObjects. When you export the rooms as GenericCityObjects, you should choose a slightly transparent coloring in the visualization export preferences.

**Comment by dikyridhlo** [comment] 2021-09-02 08:24
thank you for answer my question. @thomashkolbe 

> But you can do a "hack" and use one (or maybe a few) SQL statement(s) and copy the tuples from the ROOM table into the table GENERIC_CITYOBJECT.

is it mean i copy ROOM table to GENERIC_CITYOBJECT or use custom query when export process ?

**Comment by dikyridhlo** [comment] 2021-09-02 08:58
> you can then export them as clickable objects using the KML/COLLADA/glTF exporter. 

when using Vis-Export , am i use `SELECT objectclass_id from GENERIC_CITYOBJECT` for select only from GENERIC_CITYOBJECT or i just export it without SQL filter?

**Comment by thomashkolbe** [comment] 2021-09-02 09:08
You can export without SQL filter, if you do not have any other GenericCityObjects in your dataset. Just export the GenericCityObjects in LOD4. 

I forgot to add that after the SQL statement you will also need to do a `commit;` statement. Otherwise your updates to the database are only visible within the current psql or pgAdmin session. Only after a commit the inserted tuples will be accessible and visible to other processes like the visualization exporter.

**Comment by dikyridhlo** [comment] 2021-09-02 09:23
> 
> 
> You can export without SQL filter, if you do not have any other GenericCityObjects in your dataset. Just export the GenericCityObjects in LOD4.
> 
> I forgot to add that after the SQL statement you will also need to do a `commit;` statement. Otherwise your updates to the database are only visible within the current psql or pgAdmin session. Only after a commit the inserted tuples will be accessible and visible to other processes like the visualization exporter.

i already use commit after SQL Statement. but still got info message **No Top Level Feature** when Vis-Export.

is any possibility this issue from my GML file ?

**Comment by thomashkolbe** [comment] 2021-09-02 11:06
This simple hack will only work, if the room geometries in your CityGML file are attached as properties directly with the Room features (as lod4Solid or lod4MultiSurface). Is this the case with your dataset?

If the Room features do not have geometries, but only thematic surfaces like "FloorSurface", "CeilingSurface" and the geometries are associated only with them, you will need to collect all the individual surfaces which are related to each room (stored in the table THEMATIC_SURFACE) and create a new MultiSurface within the SURFACE_GEOMETRY table. But this is quite more tricky than just one SQL statement.

**Comment by clausnagel** [comment] 2021-09-02 11:46
There is one more thing to consider: You have to add an additional entry in the `cityobject` table for each generic city object to make this workaround work. The reason is that the exporter first searches the `cityobject` table to find the top-level city objects to be exported. 

This should be the sequence of steps to perform:
1. Query the `room` table to get the IDs of your room objects.
2. For each room, find its corresponding tuple in `cityobject` using the ID value from step 1. Create a new tuple in `cityobject` by copying the values from the room tuple (use `insert into ... as select from`). Be careful to **not** copy the ID value but create a new one using the `cityobject_seq` sequence. And do **not** copy the OBJECTCLASS_ID value but use `5` instead.
3. For each room, create a new entry in `generic_cityobject` as shown in the post from @thomashkolbe. Use the ID value just created from the sequence, and again use `5` for the OBJECTCLASS_ID.

I'm pretty sure you can do this with one SQL statement if the geometry is stored with the room objects in the `room` table as outlined by @thomashkolbe.

**Comment by dikyridhlo** [comment] 2021-09-02 12:02
thanks @thomashkolbe and @clausnagel . i will check my GML first. if geometries attributes is exist i will try the **SQL Statement** again.

**Comment by thomashkolbe** [comment] 2021-09-02 12:12
Thanks, @clausnagel, you are right; I forgot about the missing tuple in the `CITYOBJECT` table.

I mean, we are talking here about a "hack", and you could possibly simplify this by setting the `OBJECTCLASS_ID` of the tuples representing the rooms to `5`. Then the exporter would recognize them as GenericCityObjects. This could be done with such a statement:
```
insert into GENERIC_CITYOBJECT (id, objectclass_id, class, function, usage, lod4_brep_id) as 
           select id, 5, class, function, usage, lod4_solid_id from ROOM;
update CITYOBJECT set objectclass_id=5 where objectclass_id=41;
commit;
```

After these changes, you probably can no longer export the Buildings correctly. One possibility is to reverse the update statement above by reassigning `41` to the `OBJECTCLASS_ID` of those city objects, whose ID values are included in the set of ID values included in the ROOM table. 

OF COURSE, DO NOT PERFORM SUCH EXPERIMENTS ON A PRODUCTION DATABASE, BECAUSE IT MAY / WILL CORRUPT YOUR DATABASE!

**Comment by dikyridhlo** [comment] 2021-09-03 05:47
hi @thomashkolbe and @clausnagel i can show my room now. but i have another problem , my building have four floor but after i do your **hack** , only show first floor. it's possibilty on my GML or another possibilty ? thank you
![first_floor](https://user-images.githubusercontent.com/35356597/131956496-f0cef2b8-747f-452e-bed4-b14c50d7c637.jpeg)

**Comment by thomashkolbe** [comment] 2021-09-03 07:24
Please check your GML file, if more than one room is included and that their geometries are represented as a direct property (`lod4Solid` or `lod4MultiSurface`) of the `BuildingRoom` objects. The hack only works, if the geometries of all rooms are represented by `lod4Solid` properties. If some rooms use `lod4MultiSurface` instead, then you would need to modify the insert statement and add another insert statement dealing with those rooms that use `lod4MultiSurface`. For visual inspection of CityGML datasets I recommend to use the free software FZKViewer https://www.iai.kit.edu/english/1302.php.

BTW, are you sure that your visualization only shows one room? When you move the mouse pointer along the vertical extent of the building, maybe different rooms on different storeys will be highlighted then. I recommend to render the rooms using a semi-transparent color, this way you can see, if maybe more rooms are hidden in the model.

**Comment by dikyridhlo** [comment] 2021-09-03 07:38
`BTW, are you sure that your visualization only shows one room? When you move the mouse pointer along the vertical extent of the building, maybe different rooms on different storeys will be highlighted then. I recommend to render the rooms using a semi-transparent color, this way you can see, if maybe more rooms are hidden in the model.`

not only one room but only first floor (which have 12 room).

` I recommend to use the free software FZKViewer`
i already using FME and FZKViewer before import to 3dcitydb. and the result each room can be clicked for all floors.

**Comment by thomashkolbe** [comment] 2021-09-03 08:23
Can't say more without looking at the GML file. Could you provide it?

**Comment by dikyridhlo** [comment] 2021-09-03 09:02
can i know your e-mail address ?

**Comment by thomashkolbe** [comment] 2021-09-03 09:18
You'll find it here: https://www.asg.ed.tum.de/en/gis/our-team/staff/prof-thomas-h-kolbe/

**Comment by dikyridhlo** [comment] 2021-09-03 09:22
already send to your email , thanks @thomashkolbe

**Comment by thomashkolbe** [comment] 2021-09-03 10:07
Well, while the file is syntactically correct (it validates against the CityGML schema), it seems to have a number of problems. While I can visualize the model in FME, I can't using the FZKViewer nor the CityDoctor software. In FZKViewer the room geometries are not shown, which it normally does. CityDoctor issues a long list of problems including self-intersecting polygons, duplicate points in a number of LinearRings. I can't go further, because it is not clear what is causing the problem. 

Please check, if the presented hack above works with this open dataset: http://www.citygmlwiki.org/index.php?title=File:FZK-Haus-LoD4-KIT-IAI-KHH-B36-V1.gml
If it works, the problem is most likely related to your dataset. 

Also try to indentify and remove the errors from your dataset using the freely downloadable CityDoctor: https://www.citydoctor.eu/en/citydoctor_main.html

**Comment by ozaapt** [comment] 2021-09-06 08:18
hello mr.thomas and mr.clausnagel, i am on same team project with @dikyridhlo.
we try new file for test. we have check the gml file on fkzviewer and citydoctor, and no error appear

![image](https://user-images.githubusercontent.com/87305472/132182326-8479d9e7-621d-4331-90f1-66bb99e4db6b.png)
![image](https://user-images.githubusercontent.com/87305472/132182373-7ebbc457-1c28-4029-89a5-510326800195.png)
![image](https://user-images.githubusercontent.com/87305472/132182406-4ceea31a-7e3e-4930-9f58-a862cd3cfad1.png)

this building have 10 room. but when i open with viewer, only 3 room can be clicked.

![WhatsApp Image 2021-09-06 at 12 08 33](https://user-images.githubusercontent.com/87305472/132182846-c3901cca-a6ae-4774-b38b-5613b904380b.jpeg)
![WhatsApp Image 2021-09-06 at 12 08 26](https://user-images.githubusercontent.com/87305472/132182852-5e7333d2-fa3c-41d0-bfd6-0844fb379153.jpeg)
![WhatsApp Image 2021-09-06 at 12 08 19](https://user-images.githubusercontent.com/87305472/132182858-65145ef3-6b0b-48ff-9073-ea571df46323.jpeg)
![WhatsApp Image 2021-09-06 at 12 09 07](https://user-images.githubusercontent.com/87305472/132182879-58976cc9-7e63-41d8-b5d5-9671896f3c61.jpeg)

this is the sample gml i use
[sample_gml.zip](https://github.com/3dcitydb/3dcitydb-web-map/files/7114341/sample_gml.zip)

**Comment by dikyridhlo** [comment] 2021-09-07 03:02
hi @clausnagel and @thomashkolbe can you answer my team question, please?

**Comment by thomashkolbe** [comment] 2021-09-07 07:16
Hi @dikyridhlo, the file has some issues, for example are the doors and windows not included in the building object. They are also in the wrong namespace (brid:). But this should not cause a problem with the rooms. However, you will have to look for the problem for yourself by inspecting the table data. 

BTW, did you try the file I named before? Did it work? If yes, then inspect the contents of the involved tables (after having applied the hack) using pgAdmin and compare in which way the table contents look different from the contents when you have imported your model and have applied the hack then. You will need to look at every tuple in the tables and comprehend the way how CityGML data is being mapped onto the diverse tables as explained in the documentation (this is what I would do if it was my project).

**Comment by dikyridhlo** [comment] 2021-09-07 07:36
I try your file @thomashkolbe and only 5 tiles can be clicked (mark on the red checklist), it is true?
![image](https://user-images.githubusercontent.com/35356597/132303497-0853fffc-1b79-49e2-b2c0-14d6d720899a.png)

`Hi @dikyridhlo, the file has some issues, for example are the doors and windows not included in the building object. They are also in the wrong namespace (brid:). But this should not cause a problem with the rooms. However, you will have to look for the problem for yourself by inspecting the table data.`

let me check my GML file for a while.

**Comment by thomashkolbe** [comment] 2021-09-07 07:58
When you create a visualization export, only export the GenericCityObjects and not also the Buildings at the same time. You will have to configure the visualization exporter in such a way that it does not automatically pulls down the 3D objects to the ground (Altitude mode "absolute" in the "Elevation" submenu in the "VIS Export" menu). Otherwise all rooms on the higher levels will all be pulled to base height zero as shown in your figure above.

**Closed** 2024-10-11 08:08 UTC
